name: my-main-check

on: [push]
jobs:
   Install-Test-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: make setup 
      - run: make test 
      - run: make lint  
