name: my-main-check

on: [push]
jobs:
   Install-Test-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: 'npm'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK }}
      - run: make setup 
      - run: make test 
      - run: make lint  
